// Перевод ошибок сервера на русский. Каждой новой raise exception в SQL — строка здесь
// (это проверяет scripts/check_error_keys.py).

export function humanError(error) {
  const raw = error?.message || String(error || "неизвестная ошибка");
  const map = [
    ["Invalid login credentials","неверный email или пароль."],
    ["Email not confirmed","сначала подтвердите email по ссылке из письма."],
    ["User already registered","аккаунт с таким email уже существует."],
    ["School nick already registered","такой школьный ник уже зарегистрирован."],
    ["Guest name conflicts with registered player","это имя уже принадлежит зарегистрированному игроку."],
    ["Game not found","игра не найдена."],
    ["Game is full","в этой игре уже два игрока."],
    ["Cannot join your own game","нельзя присоединиться к собственной игре."],
    ["Only the room creator can close it","закрыть комнату может только ее создатель."],
    ["Game can no longer be closed","после начала боя комнату уже нельзя закрыть."],
    ["Only the second player can leave","выйти из этой комнаты сейчас нельзя."],
    ["Game can no longer be left","после начала боя выйти из комнаты уже нельзя."],
    ["Game is paused","матч приостановлен и ожидает решения администратора."],
    ["Pair already has active game","у вас уже идет незавершенный матч с этим игроком."],
    ["Game cannot be surrendered","сдаться можно только после начала боя."],
    ["Invalid game type","неизвестный режим матча."],
    ["Not a participant","вы не участвуете в этом матче."],
    ["Not your turn","сейчас ход соперника."],
    ["Cell already fired","в эту клетку уже стреляли."],
    ["Invalid fleet","сервер отклонил расстановку."],
    ["Admin required","этот раздел доступен только администратору."],
    ["Registered profile not found","зарегистрированный профиль не найден."],
    ["Game cannot be cancelled","этот матч уже завершен или закрыт."],
    ["Invalid admin game filter","неизвестный фильтр матчей."],
    ["Tournament not found","турнир не найден."],
    ["Tournament name required","введите название турнира."],
    ["Invalid tournament size","неверное количество участников."],
    ["Invalid tournament format","неверный формат турнира."],
    ["Tournament format required","сначала выберите формат турнира."],
    ["Tournament format locked","формат можно менять только до окончания приема заявок."],
    ["Invalid registration deadline","укажите будущую дату окончания регистрации."],
    ["Invalid qualifying match count","укажите от 1 до 10 квалификационных матчей."],
    ["Invalid playoff size","выберите размер плей-офф: 4, 8 или 16 участников."],
    ["Playoff size exceeds tournament limit","размер плей-офф превышает лимит участников турнира."],
    ["Playoff size exceeds participants","для выбранного плей-офф пока недостаточно участников."],
    ["Qualifying settings unavailable","для этого турнира нельзя настроить квалификацию."],
    ["Qualifying stage setup required","для этого турнира сначала нужно настроить отборочные матчи."],
    ["Qualifying settings required","сначала сохраните настройки квалификации."],
    ["Qualifying match count exceeds opponents","у каждого игрока меньше возможных соперников, чем назначенных матчей."],
    ["Qualifying schedule requires even total","с таким числом игроков нельзя назначить всем одинаковое число матчей. измените состав или количество матчей."],
    ["Qualifying stage not started","квалификация еще не запущена."],
    ["Qualifying matches not found","квалификационные матчи не найдены."],
    ["Qualifying matches incomplete","сначала завершите все квалификационные матчи."],
    ["Qualifying tiebreak required","на границе выхода в плей-офф осталось равенство. сначала проведите дополнительный матч."],
    ["Tournament has pending applications","сначала рассмотрите все ожидающие заявки."],
    ["Tournament already has matches","турнирные матчи уже созданы."],
    ["Tournament pair has active game","у одной из назначенных пар уже есть незавершенный матч. сначала завершите или закройте его."],
    ["Tournament match cannot be left","назначенный турнирный матч нельзя покинуть или закрыть."],
    ["Tournament registration closed","регистрация в этот турнир уже закрыта."],
    ["Registered profile required","в турнир можно добавить только зарегистрированного игрока."],
    ["Tournament is full","в турнире уже нет свободных мест."],
    ["Tournament already started","турнир уже начался."],
    ["Tournament already finished","завершенный турнир можно сохранить в истории или удалить навсегда."],
    ["Only finished tournament can be archived","в архив можно отправить только завершенный турнир."],
    ["Tournament already has games","нельзя перестроить сетку после создания турнирных игр."],
    ["Tournament can no longer be deleted","удалить можно только турнир, в котором еще не проводилась жеребьевка."],
    ["Tournament needs two players","для жеребьевки нужны хотя бы два участника."],
    ["Tournament match not found","турнирный матч не найден. обновите страницу."],
    ["School nick has hidden characters","в нике есть невидимые или служебные символы. наберите его заново обычными буквами."],
    ["deadlock detected","сервер в этот момент обрабатывал другое действие с этим матчем. повторите еще раз."],
    ["Tournament not active","действие доступно только пока турнир идет."],
    ["Tournament match already resolved","у этого матча уже есть результат."],
    ["Tournament match players missing","в этой паре еще нет обоих игроков."],
    ["Winner must be a match player","победителем можно назначить только игрока этой пары."],
    ["Tournament players must be verified","у кого-то из участников не подтвержден школьный ник. подтвердите ник в списке игроков или уберите участника из турнира, затем проведите жеребьевку."],
    ["Tournament needs even player count","для жеребьевки нужно четное число участников. добавьте еще одного игрока или уберите одного из списка."],
    ["Tournament application not found","заявка на этот турнир не найдена."],
    ["Tournament application not pending","эта заявка уже рассмотрена или отозвана."],
    ["Tournament application required","сначала игрок должен подать заявку на турнир."],
    ["Invalid application decision","неверное решение по заявке."],
    ["Announcement title required","введите заголовок объявления."],
    ["Announcement body required","введите текст объявления."],
    ["Invalid notification","уведомление не найдено."],
    ["Invalid school nick length","ник должен содержать от 1 до 48 символов."],
    ["Verified school nick required","для рейтинговой игры и участия в турнире сначала подтвердите школьный ник."],
    ["Too many open rooms","у вас уже 5 открытых комнат. закройте лишние, чтобы создать новую."],
    ["Rate limit exceeded","слишком много действий подряд. подождите несколько минут и попробуйте снова."],
    ["Game is not active","матч уже завершен — возможно, соперник сдался или матч закрыл администратор."],
    ["Game is not ready","соперник вышел из комнаты — дождитесь нового соперника."],
    ["Invalid cell","такой клетки на поле нет."],
    ["Target fleet missing","расстановка соперника не найдена. обновите страницу."],
    ["Opponent missing","в этом матче нет соперника."],
    ["Profile required","профиль еще не создан. обновите страницу или войдите заново."],
    ["Request id required","не удалось отправить запрос. попробуйте еще раз."],
    ["School nick required","укажите школьный ник."],
    ["Guest name required","укажите гостевое имя."],
    ["Guest profile requires anonymous user","это действие доступно только при гостевом входе."],
    ["Admin access required","этот раздел доступен только администратору."],
    ["Unknown game setting","такой настройки нет. обновите страницу."],
    ["Game setting out of range","значение вне допустимого диапазона."],
    ["Could not find the function","на сервере нет нужной функции — похоже, не применена свежая миграция базы."],
    ["Authentication required","сначала нужно войти."],
    // не ошибки сервера, а ответ браузера: сервер не ответил вовремя или нет сети
    ["TimeoutError","сервер долго не отвечает. проверьте интернет и попробуйте еще раз."],
    ["signal timed out","сервер долго не отвечает. проверьте интернет и попробуйте еще раз."],
    ["Failed to fetch","нет связи с сервером. проверьте интернет и попробуйте еще раз."],
    ["NetworkError","нет связи с сервером. проверьте интернет и попробуйте еще раз."],
    ["Load failed","нет связи с сервером. проверьте интернет и попробуйте еще раз."],
    ["action_rate_limits_pkey","сервер в этот момент обрабатывал другое ваше действие. повторите еще раз."],
  ];
  for (const [needle, text] of map) if (raw.includes(needle)) return text;
  return raw;
}
