// Общее состояние приложения: всё, что раньше было глобальными переменными app.js.
// Читать и менять из любого модуля через объект app: app.user, app.game, app.placement …
import { GAME_SETTING_DEFAULTS, TOURNAMENT_DEMO_STATES } from "./constants.js?v=130";

export const app = {
  supabase: null,
  user: null,
  profile: null,
  game: null,
  myFleet: null,
  shots: [],
  realtimeChannel: null,
  lobbyChannel: null,
  lobbyRefreshTimer: null,
  guestSetupInProgress: false,
  spectatorMode: false,
  spectatorFleets: [],
  opponentFleet: null,
  activeGamesCache: [],
  matchHistoryCache: [],
  lastLobbyRefreshAt: 0,
  profileRetryUser: null,
  profileRetries: 0,
  authError: false,
  tournamentLoadGeneration: 0,
  playerProfileGeneration: 0,
  profilesCache: new Map(),
  fruitkogAvatarCache: new Map(),
  fruitkogAvatarLoaded: new Set(),
  activeFilter: "all",
  currentView: "home",
  authReady: false,
  sessionGeneration: 0,
  activeGamesGeneration: 0,
  matchHistoryGeneration: 0,
  createGameInProgress: false,
  readyInProgress: false,
  shotInProgress: false,
  shotRevision: 0,
  surrenderInProgress: false,
  placementDrag: null,
  suppressPlacementClick: false,
  gameRefreshTimer: null,
  lastGameRefreshAt: 0,
  refreshGamePromise: null,
  refreshGameQueued: false,
  adminPlayersCache: [],
  adminGamesCache: [],
  adminGameCounts: null,
  adminGamesLegacy: false,
  adminGamesTotal: 0,
  adminGamesHasMore: false,
  adminGamesPageLoading: false,
  adminGamesViewToken: 0,
  adminPlayerFilter: "all",
  adminGameFilter: "active",
  adminCurrentGameId: null,
  adminLoading: false,
  tournamentsCache: [],
  currentTournamentId: null,
  openedArchivedTournamentId: null,
  currentTournamentBoard: null,
  adminCurrentTournamentId: null,
  adminCurrentTournamentBoard: null,
  tournamentLoading: false,
  tournamentApplicationBusy: false,
  tournamentBracketResizeObserver: null,
  tournamentBracketDrawVersion: 0,
  tournamentDemoState: TOURNAMENT_DEMO_STATES.has(new URLSearchParams(location.search).get("tournament-state"))
  ? new URLSearchParams(location.search).get("tournament-state")
  : "none",
  adminTournamentBusy: false,
  adminNotificationsCache: [],
  adminNotificationsLoading: false,
  adminNotificationsTimer: null,
  gameSettings: { ...GAME_SETTING_DEFAULTS },
  rewards: {
    mushroom_skin_unlocked: false,
    auto_miss_uses: 0,
    square_ship_uses: 0,
    selected_ship_skin: "vegetable",
  },
  rewardsUserId: null,
  gameBoosts: { game_id: null, auto_miss_enabled: false, square_ship_used: false },
  adminGameSettingsCache: [],
  placement: { ships: [], orientation: "h", selectedShipIndex: 0, selectedPlacedIndex: null },
  vegetablesEnabled: true,
};

try { app.vegetablesEnabled = localStorage.getItem("fruitkog-vegetables") !== "off"; } catch {}

