create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 48),
  account_type text not null check (account_type in ('registered','guest')),
  school_verified boolean not null default false,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_registered_name_unique
on public.profiles(lower(display_name))
where account_type='registered';

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare nick text;
begin
  if new.email is null then
    return new;
  end if;

  nick := left(regexp_replace(trim(coalesce(new.raw_user_meta_data->>'school_nick','')), '\s+', ' ', 'g'), 48);
  if length(nick) < 1 then raise exception 'School nick required'; end if;

  if exists(select 1 from public.profiles where account_type='registered' and lower(display_name)=lower(nick)) then
    raise exception 'School nick already registered';
  end if;

  insert into public.profiles(user_id,display_name,account_type)
  values(new.id,nick,'registered');

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_auth_user();

create or replace function public.is_school_nick_available(p_nick text)
returns boolean
language sql
security definer
stable
set search_path=''
as $$
  select not exists(
    select 1 from public.profiles
    where account_type='registered'
      and lower(display_name)=lower(left(regexp_replace(trim(p_nick), '\s+', ' ', 'g'),48))
  );
$$;

create or replace function public.claim_guest_name(p_name text)
returns public.profiles
language plpgsql
security definer
set search_path=''
as $$
declare
  uid uuid:=auth.uid();
  clean_name text:=left(regexp_replace(trim(p_name), '\s+', ' ', 'g'),32);
  p public.profiles%rowtype;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  if length(clean_name)<1 then raise exception 'Guest name required'; end if;

  if exists(select 1 from auth.users where id=uid and email is not null) then
    raise exception 'Guest profile requires anonymous user';
  end if;

  if exists(select 1 from public.profiles where account_type='registered' and lower(display_name)=lower(clean_name)) then
    raise exception 'Guest name conflicts with registered player';
  end if;

  insert into public.profiles(user_id,display_name,account_type)
  values(uid,clean_name,'guest')
  on conflict(user_id) do update set display_name=excluded.display_name
  returning * into p;

  return p;
end;
$$;

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  game_type text not null default 'casual' check(game_type in ('casual','rated','tournament')),
  visibility text not null default 'public' check(visibility in ('public','private')),
  player1_id uuid not null references auth.users(id) on delete restrict,
  player1_name text not null,
  player2_id uuid references auth.users(id) on delete restrict,
  player2_name text,
  player1_ready boolean not null default false,
  player2_ready boolean not null default false,
  status text not null default 'waiting' check(status in ('waiting','placing','playing','finished','cancelled')),
  current_turn uuid references auth.users(id),
  winner_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz,
  constraint games_players_different check(player2_id is null or player2_id<>player1_id)
);

create index if not exists games_lobby_idx on public.games(visibility,status,created_at desc);

create table if not exists public.fleets (
  game_id uuid not null references public.games(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  ships jsonb not null,
  created_at timestamptz not null default now(),
  primary key(game_id,owner_id)
);

create table if not exists public.shots (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  shooter_id uuid not null references auth.users(id) on delete cascade,
  target_id uuid not null references auth.users(id) on delete cascade,
  cell text not null,
  result text not null check(result in ('miss','hit','sunk','win')),
  created_at timestamptz not null default now(),
  unique(game_id,shooter_id,cell)
);

create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  status text not null default 'draft' check(status in ('draft','registration','active','finished','cancelled')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.tournament_players (
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  seed integer,
  status text not null default 'active' check(status in ('active','withdrawn','disqualified')),
  primary key(tournament_id,user_id)
);

create table if not exists public.tournament_matches (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  round_no integer not null,
  position integer not null,
  player1_id uuid references auth.users(id),
  player2_id uuid references auth.users(id),
  winner_id uuid references auth.users(id),
  game_id uuid references public.games(id),
  status text not null default 'pending' check(status in ('pending','ready','playing','awaiting_confirmation','finished','technical','cancelled')),
  next_match_id uuid references public.tournament_matches(id),
  next_slot smallint check(next_slot in (1,2)),
  created_at timestamptz not null default now(),
  unique(tournament_id,round_no,position)
);

alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.fleets enable row level security;
alter table public.shots enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_players enable row level security;
alter table public.tournament_matches enable row level security;

drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select to anon,authenticated using(true);

drop policy if exists "games readable" on public.games;
create policy "games readable" on public.games for select to authenticated
using((visibility='public' and status='waiting') or auth.uid() in (player1_id,player2_id));

drop policy if exists "own fleet readable" on public.fleets;
create policy "own fleet readable" on public.fleets for select to authenticated using(auth.uid()=owner_id);

drop policy if exists "shots readable" on public.shots;
create policy "shots readable" on public.shots for select to authenticated
using(exists(select 1 from public.games g where g.id=shots.game_id and auth.uid() in (g.player1_id,g.player2_id)));

drop policy if exists "tournaments readable" on public.tournaments;
create policy "tournaments readable" on public.tournaments for select to anon,authenticated using(status<>'draft');

drop policy if exists "tournament players readable" on public.tournament_players;
create policy "tournament players readable" on public.tournament_players for select to anon,authenticated
using(exists(select 1 from public.tournaments t where t.id=tournament_players.tournament_id and t.status<>'draft'));

drop policy if exists "tournament matches readable" on public.tournament_matches;
create policy "tournament matches readable" on public.tournament_matches for select to anon,authenticated
using(exists(select 1 from public.tournaments t where t.id=tournament_matches.tournament_id and t.status<>'draft'));

revoke all on public.profiles,public.games,public.fleets,public.shots,public.tournaments,public.tournament_players,public.tournament_matches from anon,authenticated;
grant select on public.profiles to anon,authenticated;
grant select on public.games,public.fleets,public.shots to authenticated;
grant select on public.tournaments,public.tournament_players,public.tournament_matches to anon,authenticated;

create or replace function public.assert_valid_fleet(p_ships jsonb)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  ship_rec record; cell_text text; ship_len int; ship_cells jsonb;
  ship_rows int[]; ship_cols int[];
  all_rows int[]:=array[]::int[]; all_cols int[]:=array[]::int[];
  all_ship_idx int[]:=array[]::int[]; all_cells text[]:=array[]::text[];
  r int;c int;min_r int;max_r int;min_c int;max_c int;i int;j int;
begin
  if jsonb_typeof(p_ships)<>'array' or jsonb_array_length(p_ships)<>10 then raise exception 'Invalid fleet'; end if;

  if (select count(*) from jsonb_array_elements(p_ships) s(value) where (s.value->>'length')::int=4)<>1
  or (select count(*) from jsonb_array_elements(p_ships) s(value) where (s.value->>'length')::int=3)<>2
  or (select count(*) from jsonb_array_elements(p_ships) s(value) where (s.value->>'length')::int=2)<>3
  or (select count(*) from jsonb_array_elements(p_ships) s(value) where (s.value->>'length')::int=1)<>4
  then raise exception 'Invalid fleet'; end if;

  for ship_rec in select value as ship, ordinality::int as ship_idx from jsonb_array_elements(p_ships) with ordinality loop
    ship_len:=(ship_rec.ship->>'length')::int;
    ship_cells:=ship_rec.ship->'cells';
    if ship_cells is null or jsonb_typeof(ship_cells)<>'array' or jsonb_array_length(ship_cells)<>ship_len then raise exception 'Invalid fleet'; end if;

    ship_rows:=array[]::int[]; ship_cols:=array[]::int[];
    for cell_text in select upper(value) from jsonb_array_elements_text(ship_cells) loop
      if cell_text !~ '^[A-J](10|[1-9])$' then raise exception 'Invalid fleet'; end if;
      if cell_text=any(all_cells) then raise exception 'Invalid fleet'; end if;

      c:=ascii(substr(cell_text,1,1))-ascii('A')+1;
      r:=substr(cell_text,2)::int;

      ship_rows:=array_append(ship_rows,r); ship_cols:=array_append(ship_cols,c);
      all_cells:=array_append(all_cells,cell_text); all_rows:=array_append(all_rows,r); all_cols:=array_append(all_cols,c); all_ship_idx:=array_append(all_ship_idx,ship_rec.ship_idx);
    end loop;

    select min(x),max(x) into min_r,max_r from unnest(ship_rows)x;
    select min(x),max(x) into min_c,max_c from unnest(ship_cols)x;

    if not((min_r=max_r and max_c-min_c+1=ship_len) or (min_c=max_c and max_r-min_r+1=ship_len)) then raise exception 'Invalid fleet'; end if;
  end loop;

  if array_length(all_cells,1) is not null then
    for i in 1..array_length(all_cells,1) loop
      if i<array_length(all_cells,1) then
        for j in (i+1)..array_length(all_cells,1) loop
          if all_ship_idx[i]<>all_ship_idx[j] and abs(all_rows[i]-all_rows[j])<=1 and abs(all_cols[i]-all_cols[j])<=1 then
            raise exception 'Invalid fleet';
          end if;
        end loop;
      end if;
    end loop;
  end if;
end;
$$;

create or replace function public.create_game(p_visibility text default 'public')
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare uid uuid:=auth.uid();p public.profiles%rowtype;g public.games%rowtype;new_code text;v text:=lower(trim(p_visibility));
begin
  if uid is null then raise exception 'Authentication required'; end if;
  select * into p from public.profiles where user_id=uid;
  if not found then raise exception 'Profile required'; end if;
  if v not in ('public','private') then v:='public'; end if;
  loop
    new_code:=upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
    exit when not exists(select 1 from public.games where code=new_code);
  end loop;
  insert into public.games(code,game_type,visibility,player1_id,player1_name)
  values(new_code,'casual',v,uid,p.display_name) returning * into g;
  return to_jsonb(g);
end;
$$;

create or replace function public.join_public_game(p_game_id uuid)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare uid uuid:=auth.uid();p public.profiles%rowtype;g public.games%rowtype;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  select * into p from public.profiles where user_id=uid;
  if not found then raise exception 'Profile required'; end if;
  select * into g from public.games where id=p_game_id for update;
  if not found then raise exception 'Game not found'; end if;
  if g.player1_id=uid then raise exception 'Cannot join your own game'; end if;
  if g.visibility<>'public' or g.status<>'waiting' or g.player2_id is not null then raise exception 'Game is full'; end if;
  update public.games set player2_id=uid,player2_name=p.display_name,status='placing',updated_at=now() where id=g.id returning * into g;
  return to_jsonb(g);
end;
$$;

create or replace function public.join_game_by_code(p_code text)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare uid uuid:=auth.uid();p public.profiles%rowtype;g public.games%rowtype;clean_code text:=upper(trim(p_code));
begin
  if uid is null then raise exception 'Authentication required'; end if;
  select * into p from public.profiles where user_id=uid;
  if not found then raise exception 'Profile required'; end if;
  select * into g from public.games where code=clean_code for update;
  if not found then raise exception 'Game not found'; end if;
  if g.player1_id=uid then raise exception 'Cannot join your own game'; end if;
  if g.status<>'waiting' or g.player2_id is not null then raise exception 'Game is full'; end if;
  update public.games set player2_id=uid,player2_name=p.display_name,status='placing',updated_at=now() where id=g.id returning * into g;
  return to_jsonb(g);
end;
$$;

create or replace function public.ready_with_fleet(p_game_id uuid,p_ships jsonb)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare uid uuid:=auth.uid();g public.games%rowtype;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  select * into g from public.games where id=p_game_id for update;
  if not found then raise exception 'Game not found'; end if;
  if uid not in(g.player1_id,g.player2_id) then raise exception 'Not a participant'; end if;
  if g.player2_id is null or g.status<>'placing' then raise exception 'Game is not ready'; end if;
  if (uid=g.player1_id and g.player1_ready) or (uid=g.player2_id and g.player2_ready) then raise exception 'Fleet already locked'; end if;

  perform public.assert_valid_fleet(p_ships);
  insert into public.fleets(game_id,owner_id,ships) values(g.id,uid,p_ships)
  on conflict(game_id,owner_id) do update set ships=excluded.ships,created_at=now();

  if uid=g.player1_id then update public.games set player1_ready=true,updated_at=now() where id=g.id;
  else update public.games set player2_ready=true,updated_at=now() where id=g.id; end if;

  select * into g from public.games where id=p_game_id;
  if g.player1_ready and g.player2_ready then
    update public.games
    set status='playing',current_turn=case when random()<0.5 then player1_id else player2_id end,updated_at=now()
    where id=g.id returning * into g;
  end if;
  return to_jsonb(g);
end;
$$;

create or replace function public.shoot(p_game_id uuid,p_cell text)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  uid uuid:=auth.uid();g public.games%rowtype;target_uid uuid;cell_text text:=upper(trim(p_cell));
  fleet_json jsonb;ship_rec record;hit_ship jsonb:=null;ship_len int:=0;
  prior_hits_on_ship int:=0;prior_total_hits int:=0;total_fleet_cells int:=0;result_text text;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  if cell_text !~ '^[A-J](10|[1-9])$' then raise exception 'Invalid cell'; end if;

  select * into g from public.games where id=p_game_id for update;
  if not found then raise exception 'Game not found'; end if;
  if g.status<>'playing' then raise exception 'Game is not active'; end if;
  if g.current_turn<>uid then raise exception 'Not your turn'; end if;

  if uid=g.player1_id then target_uid:=g.player2_id;
  elsif uid=g.player2_id then target_uid:=g.player1_id;
  else raise exception 'Not a participant'; end if;

  if exists(select 1 from public.shots where game_id=g.id and shooter_id=uid and cell=cell_text) then raise exception 'Cell already fired'; end if;

  select ships into fleet_json from public.fleets where game_id=g.id and owner_id=target_uid;
  if fleet_json is null then raise exception 'Target fleet missing'; end if;

  for ship_rec in select value as ship from jsonb_array_elements(fleet_json) loop
    if exists(select 1 from jsonb_array_elements_text(ship_rec.ship->'cells') c(value) where upper(c.value)=cell_text) then
      hit_ship:=ship_rec.ship; exit;
    end if;
  end loop;

  if hit_ship is null then result_text:='miss';
  else
    ship_len:=jsonb_array_length(hit_ship->'cells');

    select count(*) into prior_hits_on_ship
    from public.shots s
    where s.game_id=g.id and s.shooter_id=uid and s.target_id=target_uid and s.result in('hit','sunk','win')
      and exists(select 1 from jsonb_array_elements_text(hit_ship->'cells') c(value) where upper(c.value)=s.cell);

    select count(*) into prior_total_hits
    from public.shots s
    where s.game_id=g.id and s.shooter_id=uid and s.target_id=target_uid and s.result in('hit','sunk','win');

    select coalesce(sum(jsonb_array_length(s.value->'cells')),0)::int into total_fleet_cells
    from jsonb_array_elements(fleet_json)s(value);

    if prior_total_hits+1>=total_fleet_cells then result_text:='win';
    elsif prior_hits_on_ship+1>=ship_len then result_text:='sunk';
    else result_text:='hit'; end if;
  end if;

  insert into public.shots(game_id,shooter_id,target_id,cell,result)
  values(g.id,uid,target_uid,cell_text,result_text);

  if result_text='miss' then
    update public.games set current_turn=target_uid,updated_at=now() where id=g.id;
  elsif result_text='win' then
    update public.games set status='finished',winner_id=uid,current_turn=null,finished_at=now(),updated_at=now() where id=g.id;
  else
    update public.games set current_turn=uid,updated_at=now() where id=g.id;
  end if;

  return jsonb_build_object('result',result_text,'cell',cell_text);
end;
$$;

create or replace function public.get_leaderboard()
returns table(user_id uuid,display_name text,games_played bigint,wins bigint,losses bigint,win_rate numeric)
language sql security definer stable set search_path=''
as $$
with eligible as(
  select p.user_id,p.display_name from public.profiles p
  where p.account_type='registered' and p.school_verified=true
),
stats as(
  select e.user_id,e.display_name,
    count(g.id) filter(where g.status='finished' and g.game_type in('rated','tournament')) as games_played,
    count(g.id) filter(where g.status='finished' and g.game_type in('rated','tournament') and g.winner_id=e.user_id) as wins
  from eligible e
  left join public.games g on e.user_id in(g.player1_id,g.player2_id)
  group by e.user_id,e.display_name
)
select s.user_id,s.display_name,s.games_played,s.wins,(s.games_played-s.wins) as losses,
  case when s.games_played=0 then 0::numeric else round((s.wins::numeric*100)/s.games_played,1) end as win_rate
from stats s
order by s.wins desc,win_rate desc,s.games_played desc,lower(s.display_name);
$$;

revoke execute on function public.is_school_nick_available(text) from public;
grant execute on function public.is_school_nick_available(text) to anon,authenticated;

revoke execute on function public.claim_guest_name(text) from public,anon;
grant execute on function public.claim_guest_name(text) to authenticated;

revoke execute on function public.assert_valid_fleet(jsonb) from public,anon,authenticated;

revoke execute on function public.create_game(text) from public,anon;
revoke execute on function public.join_public_game(uuid) from public,anon;
revoke execute on function public.join_game_by_code(text) from public,anon;
revoke execute on function public.ready_with_fleet(uuid,jsonb) from public,anon;
revoke execute on function public.shoot(uuid,text) from public,anon;

grant execute on function public.create_game(text) to authenticated;
grant execute on function public.join_public_game(uuid) to authenticated;
grant execute on function public.join_game_by_code(text) to authenticated;
grant execute on function public.ready_with_fleet(uuid,jsonb) to authenticated;
grant execute on function public.shoot(uuid,text) to authenticated;

revoke execute on function public.get_leaderboard() from public;
grant execute on function public.get_leaderboard() to anon,authenticated;

do $$ begin
  alter publication supabase_realtime add table public.games;
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.shots;
exception when duplicate_object then null; end $$;
